
server:
  port: 4455
  
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/ram?createDatabaseIfNotExist=true
    username: ${Database}
    password: ${Password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true