
server:
  port: 4455
  
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/ram?createDatabaseIfNotExists=true
    username: ${Database}
    password: ${Password}
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true