
server:
  port: 4455
  
spring:
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true